### ISSUE TITLE
UV Mapping

### ISSUE THREAD

**Issue by LeonaMorro** [Outworldz/Ruth#1]
Hi,
"The goal of Ruth 2.0 is to make a high quality, 100% free mesh avatar that can use accessories from Maitreya and other quality mesh products."
I'm a SL user and that is exactlty what I would like to see. Yesterday I spend the day to investigate the current state of the Ruth mesh. From my point of view, it is already nice (I'm not a pro).
I noticed one thing that isn't nice: The current UV unwrapping. There are several areas that are heavily distorted. I thought that it should be easy (but time consuming) to fix this, so I started working at it. After a few hours I noticed a serious problem:
- The uv seams of the mesh must follow (roughly) the uv seams of the SL system Avatar: ![comparisonruthsl1](https://user-images.githubusercontent.com/11649910/33024824-76d7af20-ce0c-11e7-98ef-1b05fabb146a.png)

The most seams are doing this (more or less). The worst mismatch seems to be the croch part ![comparisonruthsl2](https://user-images.githubusercontent.com/11649910/33024864-90d4473a-ce0c-11e7-9a74-31e0eef1d894.png). As s result the female genital is misplaced.

My suggestion:
a) changing the seam from the red to the blue line as shown in the image above.
b) maybe it could further be necessary to move some verticles as shown with the blue arrow.

Thoughts?

**Comment by ingen-lab** [comment]
Hello Leona,

Thank you for taking the time to look at our project. This is my first mesh avatar project and the UV map is a result of lack of experience. I will ask around to see if anyone is willing to help us with this issue.

**Comment by LeonaMorro** [comment]
Well, of course I could do that. What I can promise is that the the uv mapping will be better than now. I also can prosmise that it will not be perfect ;)
But what about b) (moving some vertices in the crotch area)? Would that be OK for you?

**Comment by ingen-lab** [comment]
Wow! Leona, thank you so much for doing this. If you find it necessary to move some vertices around the crotch area then you may do so. I'm not too hard-pressed on keeping the edge loops pure since that area is a part of the hidden seam line.

**Comment by LeonaMorro** [comment]
Status: I finished the lower body UV Unwrap and started working on the upper body.

**Comment by LeonaMorro** [comment]
Status: I'm already happy with it. Also there is one more thing I want to try before I make a pull request: I currently have moved the vertices in the crotch area. Now I want to try if triangulate a few faces will give an equal result.
![improveduv](https://user-images.githubusercontent.com/11649910/33614484-c4945354-d9d7-11e7-95c0-e4cb675450cd.png)

**Comment by ingen-lab** [comment]
Thank you so much for doing this Leona. I am really excited to see how much she had improved and just looking at Robin Wood's template oh her I can already tell she is going to be so much better.

**Comment by ingen-lab** [comment]
I apologize, we were in the middle of releasing our first candidate and it took some time to fully evaluate the improvements that you have done. Thank you so much for your contribution and I will find a way to manually merge it with our current release.

**Comment by SundanceHaiku** [comment]
Absolutely no problem Shin.  It's pretty low on the priority list.  The UV
maps will be there in case someone wants to use them.  On another subject,
Chimera and I are just finishing up a hand pose HUD, and will get that
posted soon.  And, I'll check and see if anyone is working on toe nails and
finger nails.  I can help there too.  This is such a fantastic project.
Thanks so much for putting this all together.

**Comment by SundanceHaiku** [comment]
Hello Shin,

I'm putting the finishing touches on the fingernails & toenail mesh and a
fingernail/toenail HUD.  The assembly of the fingernail HUD is fairly
involved since it includes a color picker and a way to adjust specularity.
I will prepare instructions on how to assemble it, but the instructions
won't be ready until some time later.  I thought what I'd do is to assemble
everything with full permissions for you in Digiworldz .  I'll package the
HUD along with all mesh parts and send them to you in-world - which you can
then distribute for Open Sim folks.  Let me know if that sounds okay to you
- or it you want me to use a different procedure.

(I'm not sure how to contact you.  If this doesn't work, I'll post this on
Google +.  I just thought this note seemed better directed to you
personally rather than for open discussion.)

All Good Things,

Sundance

**Comment by typhartez** [comment]
hi Sundance

I saw your words about specularity, and I wonder how? OpenSim does not support modifying normal and specular settings by script (http://opensimulator.org/mantis/view.php?id=8282).

BTW, I'm not sure this closed issue is the best space to talk about it ^^ I suggest you post on G+ (you can post something in private, just for one contact).

**Comment by SundanceHaiku** [comment]
Still finding my way around GitHub - and obviously, this isn't the right
place to post a message.  Just disregard.  I'll find another way to get
messages to Shin and Typhaine.

**Comment by ingen-lab** [comment]
I should have open a "Help Wanted" issue for the fingernails and HUD which I'm going to do next. In my opinion, it is better to discuss specific projects here on GitHub than it is in G+
