### ISSUE TITLE
Neck distortion

### ISSUE THREAD

**Issue by HanHeld** [Outworldz/Ruth#2]
Trying the test release you dropped Nov 26 2017. 
I have posted a snapshot onto flickr, which can be found here: https://www.flickr.com/photos/61831737@N08/37942105764/in/datetaken-public/
I'm not sure if you can see it, but the neck bends at two odd spots, and it's also very (abnormally) elongated as well. 

This is wearing the included shape.

**Comment by ingen-lab** [comment]
I will be looking at this issue more closely before we finalize our first official release or at least address the body to neck connection. There is a pinch right at the connecting edges that is probably creating the distortion.

**Comment by Outworldz** [comment]
A new version has been uploaded that hopefully will address the neck issue.
