### ISSUE TITLE
part list for Ruth 2.0

### ISSUE THREAD

**Issue by LorefieldLien** [Outworldz/Ruth#20]
i have dowloaded the mesh avatar Ruth but no body partlist, only for the 2 huds.
i am not sure which one to use or it is simply not there.

**Comment by SundanceHaiku** [comment]
Hi Lorefield,

The parts list is found under the following directory:  Mesh / 08_shin's beginner script do not touch /.  The name "beginner script" is a misnomer.  (Also: "do not touch" just means "don't change this script", but you certainly can copy it and use it.   In fact, this is the script that you want to use in the HUD.)  

It's really not a "beginner's" script.  In my mind it represents some fine work on the part of Shin - particularly when Shin had to build a HUD and write the script from scratch.  There's a new script which may replace this one.  With the new one you can link the prims of the HUD in any order which makes things much easier - but that script is still under development.  It still has some bugs.  So the "beginner" script is the one you want to use - and to use it, you'll need the "parts list" which you'll find in the above directory along with the script.
