### ISSUE TITLE
How do I do an update on the Wiki

### ISSUE THREAD

**Issue by SundanceHaiku** [Outworldz/Ruth#27]
Fred or anyone.  I'm using GitHub Desktop.  Apparently, I'm suppose to be able to click on "Clone in Desktop" found our Wiki page - and the Wiki will be downloaded to the my computer.  

I do that, but I'm not seeing any new folders appearing on my hard drive under the directory: GitHub\Ruth.  It's just the same list of folders that appears under the "Code" tab in GitHub.  I thought it might be under sub-folder somewhere, but I've searched high and low and there's no Wiki.  Any suggestions on what I'm doing wrong?

I have revised assembly instructions and several other documents that ought to be moved to the Wiki but no way for me to get them there.

Thanks!

**Comment by aiaustin** [comment]
Sundance, do you know you can simly directly edit the Wiki pages?  make sure you are logged into GitHub when you view a Wiki page and the Edit/New Page buttons should show near the top right. That's how I have made Wiki changes up to now so I had not previously copied the wiki over to my local desktop. 

But I did just try the "Clone in Desktop" button on a Windo0ws system on which the GitHub Windows client is installed and that asks for a directory to which you want the Wiki copied over locally.  It relies on the GitHub tool being present so it camn be used or launched, as the underlying URL for the clone is this... github-windows://openRepo/https://github.com/Outworldz/Ruth.wiki

**Comment by SundanceHaiku** [comment]
Ai, thanks.  From what I'm understanding, I need to download the Windows
client for GitHub on which you enter terminal commands, is that correct?  I
was hoping not to have to resort to dealing with the client.  I was hoping
to keep things simple.  The "GitHub desktop" does that.  It has created a
copy of the Ruth GitHub directory on my hard drive and keeps it updated.
No terminal language required.  It's simple and has been working quite
well, allowing me to load blender files, images and documents, but for some
reason, it won't download the Wiki.  Alas, it sounds like I'm going to need
to add the client to the mix.  Just got to find the time.

**Comment by aiaustin** [comment]
I had the GitHub for desktop and Git Shell installed.. but for Ruth stuff I have not needed the command line... it all happens automagically when I click on the Clone in Desktop when on the Wiki Home page.

But really, as I said, you don't need to do that to make Wiki edits... its MUCH simpler to simply use the Edit button when on a Wiki page (yours or anyone else's in the group) at, e.g., https://github.com/Outworldz/Ruth/wiki/How-to-Assemble-Ruth-2

If you get stuck, e-mail me (ai.ai.austin@gmail.com) the updated text and any images you want to put in place and tell me which wiki page is to be changed and I can do that for you.

**Comment by SundanceHaiku** [comment]
I like being able to add illustrations and format text with an application
I'm comfortable with.  GitHub's editing and formatting capabilities are
cumbersome, at least for me.  Fortunately, GitHub fully supports PDF's.
What I've been doing is to provide a text file for folks to edit and/or add
commentary - with the intention of every so often updating the much easier
to read PDF.

I'll explore the GitHub desktop option a bit more before going to the
client.  According to their documentation, though sparse, it's supposed to
pick up the Wiki.

**Comment by SundanceHaiku** [comment]
Thank Ai for your suggestions.  In the end, I had to install the Git Bash terminal and use a clone command to get the repository loaded on my hard drive.  With the Wiki repository now in place, I can use the much-easier-to-use GitHub desktop to add or make changes in the files.  I'll keep this open for a couple of days in case anyone else is having the same problem.

**Comment by SundanceHaiku** [comment]
Problem solved.
