### ISSUE TITLE
Refinement of Upload Instructions wrt Physics Options

### ISSUE THREAD

**Issue by aiaustin** [Outworldz/Ruth#34]
@Ubitmarov, one of the main OpenSim developers, on 1st July 2018 gave some feedback on the Ruth 2.0 mesh upload options... this may mean after it is considered that the Wiki page on uploading and assembly instructions needs to be refined? 

https://github.com/Outworldz/Ruth/wiki/How-to-Assemble-Ruth-2

@Ubitmariv asks...
> Why  physics on an avatar mesh?
> 
> All the physics engines only need this if you do want physics shape type PRIM available, i.e. higher resolution collisions. Those are not needed on avatars, so no need to select anything for physics on upload. If you rez one on terrain the default convex hull is good enough.
> 
> This applies to all engines in OpenSim and in Second Life, only broken Bullet will do silly collisions from the visual parts if you do rez it inworld.
> 
> Avatar meshes should only be worried about physics if it is to be used also on Animesh objects also (at least if they do work as I think). But then the basic instructions to use lowest visual LOD for physics may give bad results, since that is only to show something on screen far way, not what physics needs.

**Comment by Outworldz** [comment]
Bullet is not broken - the collision models are all calculated by the viewer.    Without PRIM physics, Firestorm, will not render Ruth.   Ruth can be rezzed inworld as a model, too,not just as an avatar.  The proper way already been documented.

**Comment by SkullPunx** [comment]
Ok

**Comment by aiaustin** [comment]
Issue considered and no wiki changes needed. Upload instructions are still considered valid.
