### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by HanHeld** [Outworldz/Ruth#4]
If different pieces are covered by different licenses (as your included notecard leads one to believe) this needs to be spelled out in a more obvious way. 

I would suggest including a copy of each license, edited to include a note at the beginning to list what parts are covered. 
For example;

GPL.txt
This license covers the objects r_feet and r_hands
(GPL text would follow)
APL.txt
This license covers the objects r_body and r_head
(APL text would follow)

...all of these could be embedded into the main "license" card for simplicity.

**Comment by ingen-lab** [comment]
The license will be clear for the first official release.
