### ISSUE TITLE
Suggested Script Changes

### ISSUE THREAD

**Issue by SundanceHaiku** [Outworldz/Ruth#8]
A two small line changes in Alpha HUD Sender Script (r2HUD_ac_trigger.lsl) will make the script compatible in Second Life.  Changes are shown in bold below:

Line 121: string message = "ALPHA," + **(string)**primName + "," + **(string)**primFace + "," + **(string)**alphaVal;

Line 274: string message = "ALPHA," + **(string)**primName + "," + **(string)**face + "," + **(string)**alphaVal;

One last script note.  The Body Receiver Script (r2_body_receiver.lsl) requires an animation (lines 43 & 44).  The animation doesn't appear to be in the download package, and the script is unable to run without it.  To get the scripts to run, I used the those in the "test me" model available at Shin's place in digiworldz (login.digiworldz.com:8002:ingen lab).

**Comment by ingen-lab** [comment]
I will test if your suggestion will also work in OpenSim.

**Comment by SundanceHaiku** [comment]
Shin, the two stars before and after  ** (string) ** in the code snippet above were inserted by the GitHUB editor as a tag for bold font.  The two stars (**) need to be removed when you test it.  I used a bold font to show where the changes were made in the code.  The "preview" showed bold, but, for some reason it's not now showing as bold.  Probably operator error on my part.

**Comment by ingen-lab** [comment]
fixed
