### ISSUE TITLE
Vertices on the Ruth mesh model in Blender need merging

### ISSUE THREAD

**Issue by SundanceHaiku** [Outworldz/Ruth#9]
You may have caught this, but there are two locations on Ruth's neck (in the file: OSRuth2_03_alphacut.blend) where the vertices need merging.  The attached image shows the location.  
![ruthmeshvertices](https://user-images.githubusercontent.com/34669224/34471835-2217060a-ef10-11e7-8893-bc4660cdda14.jpg)

**Comment by ingen-lab** [comment]
fixed on Ada1.9
